import { PUBLIC_SUPABASE_URL, PUBLIC_SUPABASE_ANON_KEY, PUBLIC_API_URL } from '$env/static/public';

export const SUPABASE_URL = PUBLIC_SUPABASE_URL;
export const SUPABASE_ANON_KEY = PUBLIC_SUPABASE_ANON_KEY;
export const API_URL = PUBLIC_API_URL;